### Create Report
POST http://localhost:3000/reports
content-type: application/json

{
    "make":"Ford",
    "model":"Mustang",
    "year":1982,
    "mileage": 50000,
    "lng":45,
    "lat":45,
    "price": 20000
}

### Approve an existing Report
PATCH http://localhost:3000/reports/4
content-type: application/json

{
    "approved":true
}

### Get an Estimate for an existing vehicle
GET http://localhost:3000/reports?make=Ford&model=Mustang&lng=45&lat=45&mileage=20000&year=1981